#!/bin/bash
#
# Submission script for readme of DENSE repository
#
# Comments starting with #OAR are used by the resource manager if using "oarsub -S"
#
# The job reserves 8 nodes with one processor (core) per node,
# only on xeon nodes from cluster dellc6145, job duration is less than 10min
# Note : quoting style of parameters matters, follow the example
#OAR -l gpunum=1,walltime=8
#OAR -p gpu='YES' and gpucapability>='5.0'
#
# The job is submitted to the default queue
#OAR -q default
#OAR -O ./DENSE/outputs/out/OUT_%jobid%
#OAR -E ./DENSE/outputs/err/ERR_%jobid%
#OAR --array-param-file ./DENSE/scripts/param_file
#
# ! remember to set permissions for the run file 
#
# list of parallel job (each will get one line from param_file)
echo "RUN DENSE ARRAY"
source ./miniconda3/bin/activate
cd DENSE
conda env list
conda activate ${1}
conda list
wandb off
python dpdense3 loop_df_fl.py --type=pretrain --iid=${2} --lr=${3} --model=${4} --dataset=${5} --beta=${6} --seed=${7} --num_users=${8} --l2_norm_clip=${9} --noise_multiplier=${10} --minibatch_size=${11} --microbatch_size=${12} --delta=${13} --iterations=${14} --local_ep=${15} --LDP=${16}
python dpdense3 loop_df_fl.py --type=kd_train --iid=${2} --lr=${3} --model=${4} --dataset=${5} --beta=${6} --seed=${7} --batch_size=${17} --synthesis_batch_size=${18} --lr_g=${19} --bn=${20} --oh=${21} --T=${22} --save_dir=${23} --other=${24}  --adv=${25}  --epochs=${26} --g_steps=${27}