#!/bin/bash
#
# Submission script for readme of DENSE repository
#
# Comments starting with #OAR are used by the resource manager if using "oarsub -S"
#
# The job reserves 8 nodes with one processor (core) per node,
# only on xeon nodes from cluster dellc6145, job duration is less than 10min
# Note : quoting style of parameters matters, follow the example
# Notify me ! 
#OAR --notify mail:remi.godet@inria.fr
#OAR -l gpu=1, walltime=0:00:10
#OAR -p gpu_count>=1 and gpu_compute_capability_major>=5
#
# The job is submitted to the default queue
#OAR -q p4
#OAR -O ./DENSE/outputs/out/OUT_%jobid%
#OAR -E ./DENSE/outputs/err/ERR_%jobid%
#OAR --array-param-file ./DENSE/param_files/param_file
#
# ! remember to set permissions for the run file 
#
# list of parallel job (each will get one line from param_file)
./DENSE/scripts/run_parametrized "$@"